name: Release Stable

on:
  workflow_dispatch: {}
  push:
    tags: [ 'release-*' ]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions: { contents: write, packages: write }
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: pnpm/action-setup@v3
        with: { version: 9 }
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          registry-url: https://registry.npmjs.org
      - run: pnpm i
      - name: Version & Publish
        env: { NPM_TOKEN: ${{ secrets.NPM_TOKEN }} }
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          pnpm release:version
          git add -A && git commit -m "chore: version packages" || true
          git push
          pnpm -r build
          pnpm release:publish

